// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "DontTouchIt",
    platforms: [
        .iOS("17.5")
    ],
    products: [
        .iOSApplication(
            name: "DontTouchIt",
            targets: ["AppModule"],
            bundleIdentifier: "com.LeonardoPereiraMota",
            teamIdentifier: "5GYXF2FP9Y",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.purple),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight
            ],
            capabilities: [
                .camera(purposeString: "The camera is required to capture head and hand movements for interaction.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("Resources/DontTouchIt_HandActionClassifier.mlmodelc"),
                .process("Resources/Assets.xcassets")
            ]
        )
    ]
)